// Generated by https://quicktype.io

export interface BeerCollection {
  abv: number;
  description: string;
  image_url: string;
  ingredients: string[];
  name: string;
  first_brewed: string;
  short_description: string;
  votes: string;
  origin_country: string;
}
