// Generated by https://quicktype.io

export interface BeerCollection {
  abv: string;
  city: string;
  description: string;
  image_url: string;
  ingredients: string[];
  name: string;
  first_brewed: string;
  speciality: string;
  short_description: string;
  type: string;
  votes: number;
  origin_country: string;
}

