// Generated by https://quicktype.io

export interface BeerCollection {
  abv: string;
  city: string;
  description: string;
  image_url: string;
  ingredients: string[];
  name: string;
  first_brewed: string;
  speciality: string;
  type: string;
  votes: number;
  ratings: Array<BeerRatings>;
  origin_country: string;
  creation_date: string;
}

export interface BeerRatings {
  rate: number;
  userId: string;
}

